
@access_token = {{ admin_login.response.body.access_token }}

###
POST http://localhost:3000/users
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
    "name": "WRITER",
    "email": "WRITER@user.com",
    "password": "WRITER123",
    "role": "WRITER"
}

###

GET http://localhost:3000/users
Authorization: Bearer {{access_token}}

###
GET http://localhost:3000/users/cm91pvtb10000wltb3ceunn9r

###

# @name admin_login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "WRITER@user.com",
    "password": "WRITER123"
}

###
POST http://localhost:3000/posts
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
    "title": "My second post",
    "content": "This is the content of my first post.",
    "published": true
}


###
GET http://localhost:3000/posts
Authorization: Bearer {{access_token}}