
@access_token = {{ admin_login.response.body.access_token }}

###
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Admin",
    "email": "admin@user.com",
    "password": "admin123",
    "role": "ADMIN"
}

###

GET http://localhost:3000/users
Authorization: Bearer {{access_token}}

###
GET http://localhost:3000/users/cm91pvtb10000wltb3ceunn9r

###

# @name admin_login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "admin@user.com",
    "password": "admin123"
}

###
POST http://localhost:3000/posts
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
    "title": "My first post",
    "content": "This is the content of my first post.",
    "published": true
}


###
GET http://localhost:3000/posts
Authorization: Bearer {{access_token}}